name: "Terraform Pipeline Infrastructure"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - stg
          - prod

permissions:
  id-token: write
  contents: read

jobs:
  validate-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

  pipeline-infrastructure:
    needs: validate-terraform
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}

    env:
      PROJECT_NAME: terra-front

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/TerraformDeployRole
          aws-region: eu-west-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Terraform Init
        run: terraform init

      - name: Select
        run: terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }}

      - name: Import Access Control
        run: OAC_ID=$(aws cloudfront list-origin-access-controls \
          --query "OriginAccessControlList.Items[?Name=='oca-id-${PROJECT_NAME}'].Id" \
          --output text)
          if [ -n "$OAC_ID" ] && [ "$OAC_ID" != "None" ]; then
          echo "Importing existing OAC with ID $OAC_ID"
          terraform import module.cloudfront.aws_cloudfront_origin_access_control.origin_access_control $OAC_ID || true
          else
          echo "No existing OAC found"
          fi

      - name: Import S3 bucket
        run: |
          terraform state list | grep -q "module.s3.aws_s3_bucket.s3_bucket" \
          || terraform import module.s3.aws_s3_bucket.s3_bucket ${{ secrets.S3_BUCKET_NAME }}

      - name: Import CloudFront distribution
        run: |
          terraform state list | grep -q "module.cloudfront.aws_cloudfront_distribution.s3_distribution" \
          || terraform import module.cloudfront.aws_cloudfront_distribution.s3_distribution ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var="env=${{ inputs.environment }}" -input=false

      - name: Terraform Apply
        run: terraform apply -var="env=${{ inputs.environment }}" -auto-approve
